name: simple_form_arm
description: A new Flutter package form simple form builder from json data.
version: 0.0.2
homepage: https://github.com/afanray/simple_form_arm
repository: https://github.com/afanray/simpleform

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  file_picker: ^5.2.2
  image_picker: ^0.8.6
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: null
